import { mkdir, writeFile } from "node:fs/promises";
import { MemorySettlementRepository } from "../src/adapters/memoryRepository.js";
import { claimIdFor } from "../src/domain/identity.js";
import { MemoryOperatorStore, StoreBackedAuthorizationVerifier } from "../src/domain/operatorRuntime.js";
import { SettlementEngine } from "../src/domain/settlementEngine.js";
import type { EconomicAuthorization, SettlementClaim, SettlementExecutor, SettlementRecord } from "../src/domain/types.js";
import { demoAcceptance, demoContribution } from "../src/server/demoData.js";

class HarnessExecutor implements SettlementExecutor {
  calls = 0;
  mode: "success" | "failed" | "running" = "success";
  async preflight() { return { ok: true as const }; }
  async execute(claim: SettlementClaim) {
    this.calls += 1;
    if (this.mode === "failed") return { executionId: `kh_failed_${this.calls}`, status: "failed" as const, error: "keeperhub_timeout" };
    if (this.mode === "running") return { executionId: `kh_running_${this.calls}`, status: "running" as const };
    return { executionId: `kh_success_${this.calls}`, status: "success" as const, transactionHash: `0x${claim.claimId.replace("tclaim_", "").padEnd(64, "0").slice(0, 64)}` };
  }
  async reconcile(record: SettlementRecord) {
    if (record.status === "SETTLING" && record.keeperHubExecutionId?.startsWith("kh_running")) {
      record.status = "SETTLED"; record.claim.status = "SETTLED"; record.transactionHash = "0xreconciled_after_timeout";
    }
    return record;
  }
}
const policy = { version: "policy.harness.v1", token: "USDC", chainId: 84532, maxAmount: "5", requireReview: false };
async function makeEngine(executor = new HarnessExecutor(), verifier?: StoreBackedAuthorizationVerifier, repo = new MemorySettlementRepository()) { return { executor, engine: new SettlementEngine(repo, executor, policy, verifier), repo }; }
type ScenarioResult = { name: string; finalStatus: string; keeperHubExecutions: number; duplicatePayouts: number; claimIds: string[]; notes: string };
const results: ScenarioResult[] = [];
async function scenario(name: string, run: () => Promise<Omit<ScenarioResult, "name">>) { results.push({ name, ...(await run()) }); }

await scenario("duplicate webhook", async () => { const { engine, executor } = await makeEngine(); const first = await engine.handleAcceptance(demoContribution, demoAcceptance({ eventId: "delivery-a" })); const replay = await engine.handleAcceptance(demoContribution, demoAcceptance({ eventId: "delivery-b" })); return { finalStatus: replay.status, keeperHubExecutions: executor.calls, duplicatePayouts: executor.calls - 1, claimIds: [first.claim.claimId, replay.claim.claimId], notes: "Second delivery mapped to same Tender Claim." }; });
await scenario("two concurrent workers", async () => { const { engine, executor } = await makeEngine(); const [a, b] = await Promise.all([engine.handleAcceptance(demoContribution, demoAcceptance({ eventId: "worker-a" })), engine.handleAcceptance(demoContribution, demoAcceptance({ eventId: "worker-b" }))]); return { finalStatus: b.status, keeperHubExecutions: executor.calls, duplicatePayouts: executor.calls - 1, claimIds: [a.claim.claimId, b.claim.claimId], notes: "In-process lock converged workers before second execution." }; });
await scenario("repeated GitHub Action run", async () => { const { engine, executor } = await makeEngine(); const first = await engine.handleAcceptance(demoContribution, demoAcceptance({ eventId: "action-run-1" })); const rerun = await engine.handleAcceptance(demoContribution, demoAcceptance({ eventId: "action-run-2", action: "workflow_run.completed" })); return { finalStatus: rerun.status, keeperHubExecutions: executor.calls, duplicatePayouts: executor.calls - 1, claimIds: [first.claim.claimId, rerun.claim.claimId], notes: "Action rerun does not create a new economic obligation." }; });
await scenario("PR closed without acceptance", async () => { const { engine, executor } = await makeEngine(); const record = await engine.handleAcceptance(demoContribution, demoAcceptance({ accepted: false, merged: false, acceptedWorkId: undefined, mergeSha: undefined })); return { finalStatus: record.status, keeperHubExecutions: executor.calls, duplicatePayouts: 0, claimIds: [record.claim.claimId], notes: "No accepted obligation exists." }; });
await scenario("failed CI / incomplete acceptance", async () => { const { engine, executor } = await makeEngine(); const record = await engine.handleAcceptance(demoContribution, demoAcceptance({ requiredChecksPassed: false })); return { finalStatus: record.status, keeperHubExecutions: executor.calls, duplicatePayouts: 0, claimIds: [record.claim.claimId], notes: "Checks failed before settlement." }; });
await scenario("malformed recipient", async () => { const { engine, executor } = await makeEngine(); const bad = { ...demoContribution, recipientWallet: "bad", recipients: [{ wallet: "bad", amount: "1.00", role: "primary" as const }] }; const record = await engine.handleAcceptance(bad, demoAcceptance()); return { finalStatus: record.status, keeperHubExecutions: executor.calls, duplicatePayouts: 0, claimIds: [record.claim.claimId], notes: "Unsafe recipient blocked before KeeperHub." }; });
await scenario("altered economic claim requires acceptance", async () => { const { engine, executor } = await makeEngine(); const first = await engine.handleAcceptance(demoContribution, demoAcceptance()); const second = await engine.handleAcceptance({ ...demoContribution, amount: "1.25", recipients: [{ ...demoContribution.recipients[0], amount: "1.25" }] }, demoAcceptance()); return { finalStatus: second.status, keeperHubExecutions: executor.calls, duplicatePayouts: 0, claimIds: [first.claim.claimId, second.claim.claimId], notes: "Changed economics create a different Tender Claim, but no second settlement without explicit acceptance." }; });
await scenario("forged corrective authorization rejected", async () => { const { engine, executor } = await makeEngine(); const first = await engine.handleAcceptance(demoContribution, demoAcceptance()); const contribution = { ...demoContribution, amount: "1.25", recipients: [{ ...demoContribution.recipients[0], amount: "1.25" }] }; const acceptance = demoAcceptance({ acceptanceKind: "operator_correction", action: "operator.accepted" }); const forged = await engine.handleAcceptance({ ...contribution, economicAuthorization: { authorizationId: "auth-forged", kind: "corrective_claim", authorizedClaimId: claimIdFor(contribution, acceptance, policy), authorizedBy: "attacker", authorizedAt: new Date().toISOString(), linkedClaimId: first.claim.claimId, reason: "not created by operator" } }, acceptance); return { finalStatus: forged.status, keeperHubExecutions: executor.calls, duplicatePayouts: 0, claimIds: [first.claim.claimId, forged.claim.claimId], notes: "Caller-supplied authorization is rejected unless the operator store can consume it." }; });
await scenario("authorized corrective claim", async () => { const repo = new MemorySettlementRepository(); const executor = new HarnessExecutor(); const engine = new SettlementEngine(repo, executor, policy); const first = await engine.handleAcceptance(demoContribution, demoAcceptance()); const contribution = { ...demoContribution, amount: "1.25", recipients: [{ ...demoContribution.recipients[0], amount: "1.25" }] }; const acceptance = demoAcceptance({ acceptanceKind: "operator_correction", action: "operator.accepted" }); const store = new MemoryOperatorStore(); const authorization: EconomicAuthorization = { authorizationId: "auth-correction", kind: "corrective_claim", authorizedClaimId: claimIdFor(contribution, acceptance, policy), authorizedBy: "maintainer", authorizedAt: new Date().toISOString(), linkedClaimId: first.claim.claimId, reason: "accepted correction" }; await store.put(`authorization:${authorization.authorizationId}`, authorization); const authorizedEngine = new SettlementEngine(repo, executor, policy, new StoreBackedAuthorizationVerifier(store)); const corrective = await authorizedEngine.handleAcceptance({ ...contribution, economicAuthorization: authorization }, acceptance); return { finalStatus: corrective.status, keeperHubExecutions: executor.calls, duplicatePayouts: 0, claimIds: [first.claim.claimId, corrective.claim.claimId], notes: "A correction is a linked new obligation, not a rewrite." }; });
await scenario("KeeperHub timeout / unconfirmed result", async () => { const executor = new HarnessExecutor(); executor.mode = "running"; const { engine } = await makeEngine(executor); const record = await engine.handleAcceptance(demoContribution, demoAcceptance()); return { finalStatus: record.status, keeperHubExecutions: executor.calls, duplicatePayouts: 0, claimIds: [record.claim.claimId], notes: "Execution remains SETTLING; retry must reconcile the same claim." }; });
await scenario("callback/process interruption after broadcast", async () => { const executor = new HarnessExecutor(); executor.mode = "running"; const { engine } = await makeEngine(executor); const record = await engine.handleAcceptance(demoContribution, demoAcceptance()); const recovered = await engine.reconcile(record.claim.claimId); return { finalStatus: recovered?.status ?? "missing", keeperHubExecutions: executor.calls, duplicatePayouts: 0, claimIds: [record.claim.claimId], notes: "Reconciliation recovers the already-broadcast claim." }; });
await scenario("retry after success", async () => { const { engine, executor } = await makeEngine(); const settled = await engine.handleAcceptance(demoContribution, demoAcceptance()); const retry = await engine.handleAcceptance(demoContribution, demoAcceptance({ eventId: "retry-after-success" })); return { finalStatus: retry.status, keeperHubExecutions: executor.calls, duplicatePayouts: executor.calls - 1, claimIds: [settled.claim.claimId, retry.claim.claimId], notes: "Retry after success is treated as replay." }; });

const duplicatePayouts = results.reduce((sum, item) => sum + Math.max(0, item.duplicatePayouts), 0);
const summary = { generatedAt: new Date().toISOString(), scenarios: results.length, duplicatePayouts, statement: `${results.length} settlement scenarios replayed · ${duplicatePayouts} duplicate payouts`, results };
await mkdir("evidence", { recursive: true });
await writeFile("evidence/settlement-replay-harness.json", `${JSON.stringify(summary, null, 2)}\n`);
console.log(summary.statement);
